// قائمة سور القرآن الكريم مع عدد صفحات كل سورة وفق مصحف المدينة
export type SurahInfo = { number: number; name: string; pages: number };

export const SURAHS: SurahInfo[] = [
  { number: 1, name: "الفاتحة", pages: 1 },
  { number: 2, name: "البقرة", pages: 48 },
  { number: 3, name: "آل عمران", pages: 27 },
  { number: 4, name: "النساء", pages: 29 },
  { number: 5, name: "المائدة", pages: 22 },
  { number: 6, name: "الأنعام", pages: 23 },
  { number: 7, name: "الأعراف", pages: 24 },
  { number: 8, name: "الأنفال", pages: 10 },
  { number: 9, name: "التوبة", pages: 19 },
  { number: 10, name: "يونس", pages: 14 },
  { number: 11, name: "هود", pages: 15 },
  { number: 12, name: "يوسف", pages: 14 },
  { number: 13, name: "الرعد", pages: 7 },
  { number: 14, name: "إبراهيم", pages: 7 },
  { number: 15, name: "الحجر", pages: 6 },
  { number: 16, name: "النحل", pages: 14 },
  { number: 17, name: "الإسراء", pages: 12 },
  { number: 18, name: "الكهف", pages: 12 },
  { number: 19, name: "مريم", pages: 9 },
  { number: 20, name: "طه", pages: 10 },
  { number: 21, name: "الأنبياء", pages: 10 },
  { number: 22, name: "الحج", pages: 10 },
  { number: 23, name: "المؤمنون", pages: 9 },
  { number: 24, name: "النور", pages: 10 },
  { number: 25, name: "الفرقان", pages: 8 },
  { number: 26, name: "الشعراء", pages: 11 },
  { number: 27, name: "النمل", pages: 10 },
  { number: 28, name: "القصص", pages: 11 },
  { number: 29, name: "العنكبوت", pages: 9 },
  { number: 30, name: "الروم", pages: 8 },
  { number: 31, name: "لقمان", pages: 5 },
  { number: 32, name: "السجدة", pages: 4 },
  { number: 33, name: "الأحزاب", pages: 11 },
  { number: 34, name: "سبأ", pages: 8 },
  { number: 35, name: "فاطر", pages: 7 },
  { number: 36, name: "يس", pages: 7 },
  { number: 37, name: "الصافات", pages: 9 },
  { number: 38, name: "ص", pages: 7 },
  { number: 39, name: "الزمر", pages: 11 },
  { number: 40, name: "غافر", pages: 11 },
  { number: 41, name: "فصلت", pages: 8 },
  { number: 42, name: "الشورى", pages: 8 },
  { number: 43, name: "الزخرف", pages: 8 },
  { number: 44, name: "الدخان", pages: 4 },
  { number: 45, name: "الجاثية", pages: 5 },
  { number: 46, name: "الأحقاف", pages: 6 },
  { number: 47, name: "محمد", pages: 5 },
  { number: 48, name: "الفتح", pages: 6 },
  { number: 49, name: "الحجرات", pages: 3 },
  { number: 50, name: "ق", pages: 4 },
  { number: 51, name: "الذاريات", pages: 4 },
  { number: 52, name: "الطور", pages: 4 },
  { number: 53, name: "النجم", pages: 4 },
  { number: 54, name: "القمر", pages: 4 },
  { number: 55, name: "الرحمن", pages: 4 },
  { number: 56, name: "الواقعة", pages: 5 },
  { number: 57, name: "الحديد", pages: 5 },
  { number: 58, name: "المجادلة", pages: 4 },
  { number: 59, name: "الحشر", pages: 4 },
  { number: 60, name: "الممتحنة", pages: 3 },
  { number: 61, name: "الصف", pages: 2 },
  { number: 62, name: "الجمعة", pages: 2 },
  { number: 63, name: "المنافقون", pages: 2 },
  { number: 64, name: "التغابن", pages: 3 },
  { number: 65, name: "الطلاق", pages: 2 },
  { number: 66, name: "التحريم", pages: 3 },
  { number: 67, name: "الملك", pages: 4 },
  { number: 68, name: "القلم", pages: 3 },
  { number: 69, name: "الحاقة", pages: 3 },
  { number: 70, name: "المعارج", pages: 3 },
  { number: 71, name: "نوح", pages: 2 },
  { number: 72, name: "الجن", pages: 3 },
  { number: 73, name: "المزمل", pages: 2 },
  { number: 74, name: "المدثر", pages: 3 },
  { number: 75, name: "القيامة", pages: 2 },
  { number: 76, name: "الإنسان", pages: 3 },
  { number: 77, name: "المرسلات", pages: 3 },
  { number: 78, name: "النبأ", pages: 2 },
  { number: 79, name: "النازعات", pages: 2 },
  { number: 80, name: "عبس", pages: 1.5 },
  { number: 81, name: "التكوير", pages: 1 },
  { number: 82, name: "الانفطار", pages: 1 },
  { number: 83, name: "المطففين", pages: 2 },
  { number: 84, name: "الانشقاق", pages: 1 },
  { number: 85, name: "البروج", pages: 1 },
  { number: 86, name: "الطارق", pages: 0.5 },
  { number: 87, name: "الأعلى", pages: 0.5 },
  { number: 88, name: "الغاشية", pages: 1 },
  { number: 89, name: "الفجر", pages: 1.5 },
  { number: 90, name: "البلد", pages: 1 },
  { number: 91, name: "الشمس", pages: 0.5 },
  { number: 92, name: "الليل", pages: 0.5 },
  { number: 93, name: "الضحى", pages: 0.3 },
  { number: 94, name: "الشرح", pages: 0.3 },
  { number: 95, name: "التين", pages: 0.3 },
  { number: 96, name: "العلق", pages: 0.5 },
  { number: 97, name: "القدر", pages: 0.3 },
  { number: 98, name: "البينة", pages: 1 },
  { number: 99, name: "الزلزلة", pages: 0.3 },
  { number: 100, name: "العاديات", pages: 0.5 },
  { number: 101, name: "القارعة", pages: 0.3 },
  { number: 102, name: "التكاثر", pages: 0.3 },
  { number: 103, name: "العصر", pages: 0.2 },
  { number: 104, name: "الهمزة", pages: 0.3 },
  { number: 105, name: "الفيل", pages: 0.2 },
  { number: 106, name: "قريش", pages: 0.2 },
  { number: 107, name: "الماعون", pages: 0.3 },
  { number: 108, name: "الكوثر", pages: 0.2 },
  { number: 109, name: "الكافرون", pages: 0.3 },
  { number: 110, name: "النصر", pages: 0.2 },
  { number: 111, name: "المسد", pages: 0.3 },
  { number: 112, name: "الإخلاص", pages: 0.34 },
  { number: 113, name: "الفلق", pages: 0.33 },
  { number: 114, name: "الناس", pages: 0.33 },
];

export const SURAH_BY_NAME = new Map(SURAHS.map((s) => [s.name, s]));

/** يحسب مجموع الصفحات للسور المحفوظة (مقرب لأقرب صفحة) */
export function pagesFromSurahs(names: string[]): number {
  const sum = names.reduce(
    (acc, n) => acc + (SURAH_BY_NAME.get(n.trim())?.pages ?? 0),
    0
  );
  return Math.round(sum);
}

/** يحسب عدد الأحزاب التقريبي بناءً على الصفحات (604 صفحة = 60 حزب) */
export function hizbFromPages(pages: number): number {
  return Math.min(60, Math.max(0, Math.round((pages * 60) / 604)));
}
